# Generated by Django 3.0.5 on 2020-05-03 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
            ],
            options={
                'verbose_name': "Type d'artiste",
                'verbose_name_plural': "Types d'artiste",
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=6, unique=True)),
                ('locality', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Locality')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
            options={
                'verbose_name': 'Représentation',
                'verbose_name_plural': 'Représentations',
                'ordering': ['time', 'show'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('poster', models.URLField(blank=True, max_length=255, null=True)),
                ('bookable', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Spectacle',
                'verbose_name_plural': 'Spectacles',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ['types'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'Anglais'), ('FR', 'Français'), ('NL', 'Néerlandais'), ('GE', 'Allemand'), ('SP', 'Espagnol'), ('IT', 'Italien'), ('PO', 'Portugais')], default='FR', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Profil d'utilisateur",
                'verbose_name_plural': "Profils d'utilisateur",
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField()),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Representation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.AddField(
            model_name='representation',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Show'),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ArtistType')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='artisttype',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Types'),
        ),
    ]
