# Generated by Django 3.0.5 on 2020-05-18 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'En cours'), ('Completed', 'Terminée'), ('Cancelled', 'Annulée')], default='Ongoing', max_length=9),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
